image: gitpod/workspace-full

tasks:
  - init: go get -v -t -d ./...
  
vscode:
  extensions:
    - golang.go
    - vscodevim.vim

jetbrains:
  goland:
    prebuilds:
      version: stable

additionalRepositories:
  - url: https://github.com/finebiscuit/client
    checkoutLocation: client
  - url: https://github.com/finebiscuit/proto
    checkoutLocation: proto
